language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_install: ./tools/commit-validator.sh

script: ./gradlew assembleDebug

notifications:
  slack:
    rooms:
      - snowble:ZxXOtqnP8tNUs2feEobXB6kh#buildstatus
